/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.types.enums;

import javax.annotation.Generated;

/**
 * Enumeration for denoting whether an element is a template or an instance.
 */
@Generated("generated by aas-core-codegen")
public enum ModellingKind {
  /**
   * Specification of the common features of a structured element in sufficient detail
   * that such a instance can be instantiated using it
   */
  TEMPLATE,
  /**
   * Concrete, clearly identifiable element instance. Its creation and validation
   * may be guided by a corresponding element template.
   */
  INSTANCE
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
