/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.types.enums;

import javax.annotation.Generated;

/**
 * State of an event
 *
 * <p>This element is experimental and therefore may be subject to change or may be
 * removed completely in future versions of the meta-model.
 */
@Generated("generated by aas-core-codegen")
public enum StateOfEvent {
  /**
   * Event is on
   */
  ON,
  /**
   * Event is off.
   */
  OFF
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
